apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-deployment
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
      - image: busybox
        name: busybox
        tty: true
        stdin: true
        args: ["sh", "-c", "while :; do echo Greetings from k8s; sleep 1; done"]
